all:
	$(MAKE) -C pbs all
	$(MAKE) -C sge all
	$(MAKE) -C lsf all

clean:
	$(MAKE) -C pbs clean
	$(MAKE) -C sge clean
	$(MAKE) -C lsf clean

install:
	$(MAKE) -C pbs install
	$(MAKE) -C sge install
	$(MAKE) -C lsf install
