Document: mpi-start
Title: Debian mpi-start Manual
Author: <insert document author here>
Abstract: This manual describes what mpi-start is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mpi-start/mpi-start.sgml.gz

Format: postscript
Files: /usr/share/doc/mpi-start/mpi-start.ps.gz

Format: text
Files: /usr/share/doc/mpi-start/mpi-start.text.gz

Format: HTML
Index: /usr/share/doc/mpi-start/html/index.html
Files: /usr/share/doc/mpi-start/html/*.html
