all:

clean:

install:
	mkdir -p $(DESTDIR)/$(PREFIX)/etc/mpi-start
	install -m 0644 ssh.filedist $(DESTDIR)/$(PREFIX)/etc/mpi-start/
	install -m 0644 mpiexec.filedist $(DESTDIR)/$(PREFIX)/etc/mpi-start/
	install -m 0644 mpi_mt.filedist $(DESTDIR)/$(PREFIX)/etc/mpi-start/
	install -m 0644 cptoshared.filedist $(DESTDIR)/$(PREFIX)/etc/mpi-start/

