all:

clean:

install:
	mkdir -p $(DESTDIR)/$(MODULEPREFIX)
	install -m 0755 ssh.filedist $(DESTDIR)/$(MODULEPREFIX)
	install -m 0755 mpiexec.filedist $(DESTDIR)/$(MODULEPREFIX)
	install -m 0755 mpi_mt.filedist $(DESTDIR)/$(MODULEPREFIX)
	install -m 0755 cptoshared.filedist $(DESTDIR)/$(MODULEPREFIX)

