all:

clean:

install:
	mkdir -p $(DESTDIR)/$(MODULEPREFIX)
	install -m 0644 ssh.filedist $(DESTDIR)/$(MODULEPREFIX)
	install -m 0644 mpiexec.filedist $(DESTDIR)/$(MODULEPREFIX)
	install -m 0644 mpi_mt.filedist $(DESTDIR)/$(MODULEPREFIX)
	install -m 0644 cptoshared.filedist $(DESTDIR)/$(MODULEPREFIX)

