all:

clean:

install:
	mkdir -p $(destdir)/$(moduledir)
	install -m 0755 ssh.filedist $(destdir)/$(moduledir)
	install -m 0755 mpiexec.filedist $(destdir)/$(moduledir)
	install -m 0755 mpi_mt.filedist $(destdir)/$(moduledir)
	install -m 0755 cptoshared.filedist $(destdir)/$(moduledir)

